// <auto-generated />
using System;
using ManufacturingInventory.Infrastructure.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ManufacturingInventory.Infrastructure.Migrations
{
    [DbContext(typeof(ManufacturingContext))]
    [Migration("20200222181243_fixedSeed")]
    partial class fixedSeed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Alert", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("AlertTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<int>("PartInstanceId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("PartInstanceId");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistributorId")
                        .HasColumnType("int");

                    b.Property<bool>("Expires")
                        .HasColumnType("bit");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PartId")
                        .HasColumnType("int");

                    b.Property<int?>("PartInstanceId")
                        .HasColumnType("int");

                    b.Property<int?>("PriceId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SourceReference")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ValidThough")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DistributorId");

                    b.HasIndex("ManufacturerId");

                    b.HasIndex("PartId");

                    b.HasIndex("PartInstanceId");

                    b.HasIndex("PriceId")
                        .IsUnique()
                        .HasFilter("[PriceId] IS NOT NULL");

                    b.ToTable("Attachments");
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.BubblerParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("DateInstalled")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateRemoved")
                        .HasColumnType("datetime2");

                    b.Property<double>("GrossWeight")
                        .HasColumnType("float");

                    b.Property<double>("Measured")
                        .HasColumnType("float");

                    b.Property<double>("NetWeight")
                        .HasColumnType("float");

                    b.Property<double>("Tare")
                        .HasColumnType("float");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("BubblerParameters");
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Category");
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CountryCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DistributorId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistributorId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Distributor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Distributors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Boron Nitride Parts",
                            Name = "LSP Industrial Ceramics Inc."
                        },
                        new
                        {
                            Id = 2,
                            Description = "Sapphire Parts",
                            Name = "Rayotek"
                        },
                        new
                        {
                            Id = 3,
                            Description = "SiC & TaC Coated Graphite parts",
                            Name = "Mersen"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Original Aixtron Parts",
                            Name = "Aixtron"
                        },
                        new
                        {
                            Id = 5,
                            Description = "All Quartz Parts",
                            Name = "Quality Quartz Engineering "
                        },
                        new
                        {
                            Id = 6,
                            Description = "",
                            Name = "Akzo Nobel"
                        });
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.InstanceParameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("MinValue")
                        .HasColumnType("float");

                    b.Property<int>("ParameterId")
                        .HasColumnType("int");

                    b.Property<int>("PartInstanceId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<double>("SafeValue")
                        .HasColumnType("float");

                    b.Property<bool>("Tracked")
                        .HasColumnType("bit");

                    b.Property<double>("Value")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("ParameterId");

                    b.HasIndex("PartInstanceId");

                    b.ToTable("InstanceParameter");
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Locations");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Location");
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Manufacturer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Manufacturers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Mersen deals with all SiC coated & TaC coated graphite parts.",
                            Name = "Mersen"
                        });
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Parameter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("UnitId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UnitId");

                    b.ToTable("Parameters");
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Part", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("DefaultToCostReported")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HoldsBubblers")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("UsageId")
                        .HasColumnType("int");

                    b.Property<int?>("WarehouseId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.HasIndex("UsageId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("Parts");
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.PartInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BatchNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("BubblerParameterId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ConditionId")
                        .HasColumnType("int");

                    b.Property<bool>("CostReported")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsBubbler")
                        .HasColumnType("bit");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<int>("MinQuantity")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int?>("PartTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("PriceId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SafeQuantity")
                        .HasColumnType("int");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SkuNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TotalCost")
                        .HasColumnType("float");

                    b.Property<double>("UnitCost")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("BubblerParameterId")
                        .IsUnique()
                        .HasFilter("[BubblerParameterId] IS NOT NULL");

                    b.HasIndex("ConditionId");

                    b.HasIndex("LocationId");

                    b.HasIndex("PartId");

                    b.HasIndex("PartTypeId");

                    b.HasIndex("PriceId");

                    b.ToTable("PartInstances");
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.PartManufacturer", b =>
                {
                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int>("ManufacturerId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("PartId", "ManufacturerId");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("PartManufacturers");
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.PartPrice", b =>
                {
                    b.Property<int>("PartId")
                        .HasColumnType("int");

                    b.Property<int>("PriceId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("PartId", "PriceId");

                    b.HasIndex("PriceId");

                    b.ToTable("PartPrices");
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Full Inventory Privileges and User Control",
                            Name = "InventoryAdminAccount"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Inventory View Only",
                            Name = "InventoryUserAccount"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Full Inventory Privileges",
                            Name = "InventoryUserFullAccount"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Inventory Check In/Check Out/Create",
                            Name = "InventoryUserLimitedAccount"
                        });
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Price", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DistributorId")
                        .HasColumnType("int");

                    b.Property<double>("LeadTime")
                        .HasColumnType("float");

                    b.Property<int>("MinOrder")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("UnitCost")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DistributorId");

                    b.ToTable("Prices");
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.PriceLog", b =>
                {
                    b.Property<int>("PriceId")
                        .HasColumnType("int");

                    b.Property<int>("PartInstanceId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.HasKey("PriceId", "PartInstanceId");

                    b.HasIndex("PartInstanceId");

                    b.ToTable("PriceLogs");
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("In")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Out")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("InventoryAction")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<double>("MeasuredWeight")
                        .HasColumnType("float");

                    b.Property<int>("PartInstanceId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("ReferenceTransactionId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("SessionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalCost")
                        .HasColumnType("float");

                    b.Property<double>("UnitCost")
                        .HasColumnType("float");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("LocationId");

                    b.HasIndex("PartInstanceId");

                    b.HasIndex("ReferenceTransactionId")
                        .IsUnique()
                        .HasFilter("[ReferenceTransactionId] IS NOT NULL");

                    b.HasIndex("SessionId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Exponent")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Power")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Units");
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EncryptedPassword")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Extension")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("IV")
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("Key")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PermissionId")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<bool>("StorePassword")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FirstName = "Andrew",
                            LastName = "Elmendorf",
                            PermissionId = 1,
                            StorePassword = false,
                            UserName = "AElmendo"
                        });
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.UserAlert", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("AlertId")
                        .HasColumnType("int");

                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("UserId", "AlertId");

                    b.HasIndex("AlertId");

                    b.ToTable("UserAlerts");
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Condition", b =>
                {
                    b.HasBaseType("ManufacturingInventory.Infrastructure.Model.Entities.Category");

                    b.HasDiscriminator().HasValue("Condition");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A new Part",
                            Name = "New"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Part that has been used and returned to inventory",
                            Name = "Used"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A part returned to inventory and needs cleaning. i.e. Satellites",
                            Name = "Need Cleaning"
                        },
                        new
                        {
                            Id = 4,
                            Description = "A part returned to inventory in need of repair/refurbish",
                            Name = "Needs Repair"
                        },
                        new
                        {
                            Id = 5,
                            Description = "A part in inventory that was repaired/refurbished",
                            Name = "Refurbished"
                        },
                        new
                        {
                            Id = 6,
                            Description = "A part's stock is depleted. No additional stock will be added or returned",
                            Name = "Depleted"
                        });
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Organization", b =>
                {
                    b.HasBaseType("ManufacturingInventory.Infrastructure.Model.Entities.Category");

                    b.HasDiscriminator().HasValue("Organization");

                    b.HasData(
                        new
                        {
                            Id = 7,
                            Description = "",
                            Name = "Raw Materials"
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            Name = "Supplies"
                        });
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.PartType", b =>
                {
                    b.HasBaseType("ManufacturingInventory.Infrastructure.Model.Entities.Category");

                    b.HasDiscriminator().HasValue("PartType");

                    b.HasData(
                        new
                        {
                            Id = 13,
                            Description = "",
                            Name = "1x2-short"
                        },
                        new
                        {
                            Id = 14,
                            Description = "",
                            Name = "1x2-long"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Used only for System B01",
                            Name = "System B01"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Used only for System B02",
                            Name = "System B02"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Used only for System B03",
                            Name = "System B03"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Used only for System B04",
                            Name = "System B04"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Used only for System B05",
                            Name = "System B05"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Used only for System B06",
                            Name = "System B06"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Used only for System B07",
                            Name = "System B07"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Used only for System A01",
                            Name = "System A01"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Used only for System A02",
                            Name = "System A02"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Used only for System A03",
                            Name = "System A03"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Used only for System A04",
                            Name = "System A04"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Used only for System A05",
                            Name = "System A05"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Used only for System A06",
                            Name = "System A06"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Used only for System A07",
                            Name = "System A07"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Used only for System C01",
                            Name = "System C01"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Used only for System C02",
                            Name = "System C02"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Used only for System C03",
                            Name = "System C03"
                        },
                        new
                        {
                            Id = 32,
                            Description = "Used only for System C04",
                            Name = "System C04"
                        },
                        new
                        {
                            Id = 33,
                            Description = "Used only for System C05",
                            Name = "System C05"
                        },
                        new
                        {
                            Id = 34,
                            Description = "Used only for System C06",
                            Name = "System C06"
                        },
                        new
                        {
                            Id = 35,
                            Description = "Used only for System C07",
                            Name = "System C07"
                        },
                        new
                        {
                            Id = 36,
                            Description = "Used only for System C08",
                            Name = "System C08"
                        },
                        new
                        {
                            Id = 37,
                            Description = "Used only for System C09",
                            Name = "System C09"
                        },
                        new
                        {
                            Id = 38,
                            Description = "Used only for System C10",
                            Name = "System C10"
                        },
                        new
                        {
                            Id = 39,
                            Description = "Used only for System C11",
                            Name = "System C11"
                        });
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Usage", b =>
                {
                    b.HasBaseType("ManufacturingInventory.Infrastructure.Model.Entities.Category");

                    b.HasDiscriminator().HasValue("Usage");

                    b.HasData(
                        new
                        {
                            Id = 9,
                            Description = "Used on all Epi Systems",
                            Name = "All Systems"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Used on A Systems",
                            Name = "A Systems"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Used on B Systems",
                            Name = "B Systems"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Used on C Systems",
                            Name = "C Systems"
                        });
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Consumer", b =>
                {
                    b.HasBaseType("ManufacturingInventory.Infrastructure.Model.Entities.Location");

                    b.HasDiscriminator().HasValue("Consumer");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            Description = "Reactor B01",
                            Name = "System B01"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Reactor B02",
                            Name = "System B02"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Reactor B03",
                            Name = "System B03"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Reactor B04",
                            Name = "System B04"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Reactor B05",
                            Name = "System B05"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Reactor B06",
                            Name = "System B06"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Reactor B07",
                            Name = "System B07"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Reactor A01",
                            Name = "System A01"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Reactor A02",
                            Name = "System A02"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Reactor A03",
                            Name = "System A03"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Reactor A04",
                            Name = "System A04"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Reactor A05",
                            Name = "System A05"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Reactor A06",
                            Name = "System A06"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Reactor A07",
                            Name = "System A07"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Reactor C01",
                            Name = "System C01"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Reactor C02",
                            Name = "System C02"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Reactor C03",
                            Name = "System C03"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Reactor C04",
                            Name = "System C04"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Reactor C05",
                            Name = "System C05"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Reactor C06",
                            Name = "System C06"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Reactor C07",
                            Name = "System C07"
                        },
                        new
                        {
                            Id = 27,
                            Description = "Reactor C08",
                            Name = "System C08"
                        },
                        new
                        {
                            Id = 28,
                            Description = "Reactor C09",
                            Name = "System C09"
                        },
                        new
                        {
                            Id = 29,
                            Description = "Reactor C10",
                            Name = "System C10"
                        },
                        new
                        {
                            Id = 30,
                            Description = "Reactor C11",
                            Name = "System C11"
                        },
                        new
                        {
                            Id = 31,
                            Description = "Generic Consumer for cost reporting",
                            Name = "Epi Process"
                        });
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Warehouse", b =>
                {
                    b.HasBaseType("ManufacturingInventory.Infrastructure.Model.Entities.Location");

                    b.HasDiscriminator().HasValue("Warehouse");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "",
                            Name = "Epi System Parts"
                        },
                        new
                        {
                            Id = 2,
                            Description = "",
                            Name = "Gas Bay"
                        },
                        new
                        {
                            Id = 3,
                            Description = "",
                            Name = "Epi Chase"
                        },
                        new
                        {
                            Id = 4,
                            Description = "",
                            Name = "Process Lab"
                        },
                        new
                        {
                            Id = 5,
                            Description = "",
                            Name = "Back Warehouse"
                        });
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Alert", b =>
                {
                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.PartInstance", "PartInstance")
                        .WithMany()
                        .HasForeignKey("PartInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Attachment", b =>
                {
                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Distributor", "Distributor")
                        .WithMany("Attachments")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Attachments")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Part", "Part")
                        .WithMany("Attachments")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.PartInstance", "PartInstance")
                        .WithMany("Attachments")
                        .HasForeignKey("PartInstanceId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Price", "Price")
                        .WithOne("Attachment")
                        .HasForeignKey("ManufacturingInventory.Infrastructure.Model.Entities.Attachment", "PriceId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Contact", b =>
                {
                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Distributor", "Distributor")
                        .WithMany("Contacts")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Manufacturer", "Manufacturer")
                        .WithMany("Contacts")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.InstanceParameter", b =>
                {
                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Parameter", "Parameter")
                        .WithMany("InstanceParameters")
                        .HasForeignKey("ParameterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.PartInstance", "PartInstance")
                        .WithMany()
                        .HasForeignKey("PartInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Parameter", b =>
                {
                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Unit", "Unit")
                        .WithMany("Parameters")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Part", b =>
                {
                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Organization", "Organization")
                        .WithMany("Parts")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Usage", "Usage")
                        .WithMany("Parts")
                        .HasForeignKey("UsageId");

                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Warehouse", "Warehouse")
                        .WithMany("StoredParts")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.PartInstance", b =>
                {
                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.BubblerParameter", "BubblerParameter")
                        .WithOne("PartInstance")
                        .HasForeignKey("ManufacturingInventory.Infrastructure.Model.Entities.PartInstance", "BubblerParameterId");

                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Condition", "Condition")
                        .WithMany("PartInstances")
                        .HasForeignKey("ConditionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Location", "CurrentLocation")
                        .WithMany("ItemsAtLocation")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Part", "Part")
                        .WithMany("PartInstances")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.PartType", "PartType")
                        .WithMany("PartInstances")
                        .HasForeignKey("PartTypeId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Price", "Price")
                        .WithMany("PartInstances")
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.PartManufacturer", b =>
                {
                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Manufacturer", "Manufacturer")
                        .WithMany("PartManufacturers")
                        .HasForeignKey("ManufacturerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Part", "Part")
                        .WithMany("PartManufacturers")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.PartPrice", b =>
                {
                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Part", "Part")
                        .WithMany("PartPrices")
                        .HasForeignKey("PartId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Price", "Price")
                        .WithMany("PartPrices")
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Price", b =>
                {
                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Distributor", "Distributor")
                        .WithMany("Prices")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.PriceLog", b =>
                {
                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.PartInstance", "PartInstance")
                        .WithMany("PriceLogs")
                        .HasForeignKey("PartInstanceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Price", "Price")
                        .WithMany("PriceLogs")
                        .HasForeignKey("PriceId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Session", b =>
                {
                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.User", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.Transaction", b =>
                {
                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Location", "Location")
                        .WithMany("Transactions")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.PartInstance", "PartInstance")
                        .WithMany("Transactions")
                        .HasForeignKey("PartInstanceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Transaction", "ReferenceTransaction")
                        .WithOne()
                        .HasForeignKey("ManufacturingInventory.Infrastructure.Model.Entities.Transaction", "ReferenceTransactionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Session", "Session")
                        .WithMany("Transactions")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.User", b =>
                {
                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Permission", "Permission")
                        .WithMany("Users")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("ManufacturingInventory.Infrastructure.Model.Entities.UserAlert", b =>
                {
                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.Alert", "Alert")
                        .WithMany("UserAlerts")
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ManufacturingInventory.Infrastructure.Model.Entities.User", "User")
                        .WithMany("UserAlerts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
